POST http://localhost:8080/api/account/register?email=nguyenhaanhkiem@gmail.com&password=123456&name=ABC

###
POST http://localhost:8080/api/account/login?email=nguyenhaanhkiem@gmail.com&password=123456


###
PATCH http://localhost:8080/api/account/update-account 
content-Type: application/json

{
    "jwt": "ak",
    "key": {
        "Email": "satthuid@gmail.com"
    },
    "account": {
        "Email": "satthuid@gmail.com",
        "Name": "Kiem",
        "Phone": "body.Phone",
        "Year": "body.Year",
        "Introduce": "body.Introduce",
        "Birth": "body.Birth",
        "Gender": "body.Gender"
    }
}

###
PATCH http://localhost:8080/api/account/update-account-pass 
content-Type: application/json

{
    "Email": "satthuid@gmail.com",
    "Password": "12345",
    "PasswordNew": "123456"
}